remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

image: /Portfolio-Gateway/assets/images/Josh_png.png
title: [Welcome! I'm so glad you made it!]
description: [Here you will find a small showcase of my portfolio and a little something about me.]
