remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

image: /Portfolio-Gateway/assets/images/Josh_png.png
title: [Welcome! I'm so glad you made it!]
description: [Feel free to browse]
titles_from_headings:
enabled: false
